default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: finance_grinder
  password: <%= ENV['FINANCE_GRINDER_DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: finance_grinder_development

test:
  <<: *default
  database: finance_grinder_test

production:
  <<: *default
  database: finance_grinder_production
